### ISSUE TITLE
results on OUMVLP

### ISSUE THREAD

**Issue by ChaoFan996** [OliverHxh/CSTL#3]
Hi, thanks for your excellent work!
Would you offer me the rank-1 accuracy on OUMVLP with excluding those sequences owing no gallery?
You can replace [this line](https://github.com/OliverHxh/CSTL/blob/6648cb454c15d46c52ad44ea86de3c0349dafae7/model/utils/evaluator.py#L37) with:
`pseq_mask = np.isin(seq_type, probe_seq) & np.isin(view, [probe_view]) & np.isin(label, gallery_y)`
to get it.

**Comment by OliverHxh** [comment]
We already present the journal version:&nbsp;https://arxiv.org/abs/2204.03270 , where you can get what you want in Table. 3.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OliverHxh/CSTL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 晚上9:31
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OliverHxh/CSTL] results on OUMVLP (Issue #3)





 
Hi, thanks for your excellent work!
 Would you offer me the rank-1 accuracy on OUMVLP with excluding those sequences owing no gallery?
 You can replace this line with:
 pseq_mask = np.isin(seq_type, probe_seq) &amp; np.isin(view, [probe_view]) &amp; np.isin(label, gallery_y)
 to get it.

**Comment by ChaoFan996** [comment]
Thanks a lot ~
